language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t conradmaker/prac-full-app -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true conradmaker/prac-full-app yarn test

after_success:
  - docker build -t conradmaker/docker-client ./client
  - docker build -t conradmaker/docker-server ./server
  - docker build -t conradmaker/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push conradmaker/docker-client
  - docker push conradmaker/docker-server
  - docker push conradmaker/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-full-app"
  env: "Dockerfullapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-840838586021"
  bucket_path: "docker-full-app"
  on:
    branch: master
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY