# EB에서 사용
version: "3"
services:
  fe:
    image: conradmaker/docker-client
    container_name: fe
    # build: 
    #   dockerfile: Dockerfile.dev
    #   context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true

  be:
    image: conradmaker/docker-server
    container_name: be
    # build: 
    #   dockerfile: Dockerfile.dev
    #   context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      MYSQL_HOST: $MYSQL_HOST 
      MYSQL_USER: $MYSQL_USER 
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PORT: $MYSQL_PORT   

  nginx:
    image: conradmaker/docker-nginx
    container_name: nginx
    restart: always
    # build: 
    #   dockerfile: Dockerfile
    #   context: ./nginx
    ports:
      - "3000:80"
